name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run_tests:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2
        
      - name: Build solution
        run: msbuild Calculator.sln -target:Calculator,CalculatorTests
      
      - name: Run tests
        run: ./x64/Debug/CalculatorTests.exe

  auto_merge:
    needs: run_tests
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    steps:
      - name: Debug event
        run: echo "Mergeable state: ${{ github.event.pull_request.mergeable_state }}"
      
      - name: Auto-merge pull request
        uses: peter-evans/auto-merge@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}